### PR TITLE
Fix Allocation Delay

### LINKED ISSUE #5: [Bug] Error `UninitializedAllocationDelay()` thrown in second run of docker compose
For some reason, running `docker compose up` the second time from a fresh clone causes the `UninitiallizedAllocationDelay()` error to be thrown.

The error happens in the `RegisterOperator.s.sol` script when we call `modifyAllocations` on `AllocationManager`

This seems to show that the runs are not really stateless, needs further investigation

A work around is to call `setAllocationDelay` in `RegisterOperator.s.sol` (see: https://github.com/BreadchainCoop/bls-middleware/commit/8e71c6be537256db8e6f434dab9de816f3cda6fd)

### PR DESCRIPTION
**Pull request by hudsonhrh**
calls set allocation delay. need to add allocation manager address which is now included in the example env 

closes #5

### CODE REVIEW

**Comment by rubydusa** [comment]
@hudsonhrh you didn't call the correct function in impersonate.
There is an allocation delay, and allocation delay delay (allocation configuration delay). The later one is the problem

Also just checked - `ALLOCATION_CONFIGURATION_DELAY` is immutable so the only way to change it is with set code cheatcodes and imo it'd be a time sink that's not worth the effort

I'll try regardless maybe now the local environment works and lyk

**Comment by RonTuretzky** [comment]
> @hudsonhrh you didn't call the correct function in impersonate. There is an allocation delay, and allocation delay delay (allocation configuration delay). The later one is the problem
> 
> Also just checked - `ALLOCATION_CONFIGURATION_DELAY` is immutable so the only way to change it is with set code cheatcodes and imo it'd be a time sink that's not worth the effort
> 
> I'll try regardless maybe now the local environment works and lyk

are you fucking kidding me holy shit 

so basically we are stuck with evm_increaseTime ?

**Comment by rubydusa** [comment]
Ig

**Comment by hudsonhrh** [comment]
i think what i did is the right allocation delay 

> @hudsonhrh you didn't call the correct function in impersonate. There is an allocation delay, and allocation delay delay (allocation configuration delay). The later one is the problem
> 
> Also just checked - `ALLOCATION_CONFIGURATION_DELAY` is immutable so the only way to change it is with set code cheatcodes and imo it'd be a time sink that's not worth the effort
> 
> I'll try regardless maybe now the local environment works and lyk

i think this is alreayd set to 0 in the core deployment lib and im pretty sure its not the issue

```
        address allocationManagerImpl = address(
            new AllocationManager(
                IDelegationManager(result.delegationManager),
                IPauserRegistry(result.pauserRegistry),
                IPermissionController(result.permissionController),
                // IAVSDirectory(result.avsDirectory),
                uint32(0), // _DEALLOCATION_DELAY
                uint32(0), // _ALLOCATION_CONFIGURATION_DELAY
                EIGENLAYER_VERSION
            )
        );
```

the delay i just set fixed it on my end let me know if it works locally for you

**Comment by RonTuretzky** [comment]
> i think what i did is the right allocation delay
> 
> > @hudsonhrh you didn't call the correct function in impersonate. There is an allocation delay, and allocation delay delay (allocation configuration delay). The later one is the problem
> > Also just checked - `ALLOCATION_CONFIGURATION_DELAY` is immutable so the only way to change it is with set code cheatcodes and imo it'd be a time sink that's not worth the effort
> > I'll try regardless maybe now the local environment works and lyk
> 
> i think this is alreayd set to 0 in the core deployment lib and im pretty sure its not the issue
> 
> ```
>         address allocationManagerImpl = address(
>             new AllocationManager(
>                 IDelegationManager(result.delegationManager),
>                 IPauserRegistry(result.pauserRegistry),
>                 IPermissionController(result.permissionController),
>                 // IAVSDirectory(result.avsDirectory),
>                 uint32(0), // _DEALLOCATION_DELAY
>                 uint32(0), // _ALLOCATION_CONFIGURATION_DELAY
>                 EIGENLAYER_VERSION
>             )
>         );
> ```
> 
> the delay i just set fixed it on my end let me know if it works locally for you

we are not deploying the core though, we are using what's already on testnet and it's not set to 0 I'm pretty sure

**Comment by hudsonhrh** [comment]
> > i think what i did is the right allocation delay
> > > @hudsonhrh you didn't call the correct function in impersonate. There is an allocation delay, and allocation delay delay (allocation configuration delay). The later one is the problem
> > > Also just checked - `ALLOCATION_CONFIGURATION_DELAY` is immutable so the only way to change it is with set code cheatcodes and imo it'd be a time sink that's not worth the effort
> > > I'll try regardless maybe now the local environment works and lyk
> > 
> > 
> > i think this is alreayd set to 0 in the core deployment lib and im pretty sure its not the issue
> > ```
> >         address allocationManagerImpl = address(
> >             new AllocationManager(
> >                 IDelegationManager(result.delegationManager),
> >                 IPauserRegistry(result.pauserRegistry),
> >                 IPermissionController(result.permissionController),
> >                 // IAVSDirectory(result.avsDirectory),
> >                 uint32(0), // _DEALLOCATION_DELAY
> >                 uint32(0), // _ALLOCATION_CONFIGURATION_DELAY
> >                 EIGENLAYER_VERSION
> >             )
> >         );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the delay i just set fixed it on my end let me know if it works locally for you
> 
> we are not deploying the core though, we are using what's already on testnet and it's not set to 0 I'm pretty sure

here is the code where the error comes from its checking the allocationDelay per operator 

```
        // Check that the operator exists and has configured an allocation delay
        uint32 operatorAllocationDelay;
        {
            (bool isSet, uint32 delay) = getAllocationDelay(operator);
            require(isSet, UninitializedAllocationDelay());
            operatorAllocationDelay = delay;
        }
```

**Comment by rubydusa** [comment]
yeah there is no call to core deployment lib

**Comment by hudsonhrh** [comment]
just confiremd again it works for me locally. does it work for either of you? when i remove the setAllocationDelay it fails with the usual error

**Comment by hudsonhrh** [comment]
> yeah there is no call to core deployment lib

im confused on what is even causing this error hoenstly now because [this](https://github.com/BreadchainCoop/eigenlayer-bls-local/pull/9#issuecomment-2895568275) is where the error is called which is refrencing the delay I have this fix set. this version has no waiting or manipulating time and it works just fine

**Comment by rubydusa** [comment]
> > yeah there is no call to core deployment lib
> 
> im confused on what is even causing this error hoenstly now because [this](https://github.com/BreadchainCoop/eigenlayer-bls-local/pull/9#issuecomment-2895568275) is where the error is called which is refrencing the delay I have this fix set. this version has no waiting or manipulating time and it works just fine

AFAIU it's because the isSet flag is by default false, and it gets applied only after the configuration delay. This is also what someone from eigen told me if operators have to wait two and a half weeks before joining slashable quorums, and they told me yes.

I have no fucking idea why your call to `setAllocationDelay` works, because it's also called on registration by the `DelegationManager`

**Comment by RonTuretzky** [comment]
> > > yeah there is no call to core deployment lib
> > 
> > 
> > im confused on what is even causing this error hoenstly now because [this](https://github.com/BreadchainCoop/eigenlayer-bls-local/pull/9#issuecomment-2895568275) is where the error is called which is refrencing the delay I have this fix set. this version has no waiting or manipulating time and it works just fine
> 
> AFAIU it's because the isSet flag is by default false, and it gets applied only after the configuration delay. This is also what someone from eigen told me if operators have to wait two and a half weeks before joining slashable quorums, and they told me yes.
> 
> I have no fucking idea why your call to `setAllocationDelay` works, because it's also called on registration by the `DelegationManager`

i think the isSet method adds the 2 week delay check shit

**Comment by rubydusa** [comment]
@hudsonhrh what is this error?
```console
eigenlayer-1  |   [4161] RegisterOperator::run()
eigenlayer-1  |     ├─ [0] VM::envString("OPERATOR_ID") [staticcall]
eigenlayer-1  |     │   └─ ← [Revert] vm.envString: environment variable "OPERATOR_ID" not found
eigenlayer-1  |     └─ ← [Revert] vm.envString: environment variable "OPERATOR_ID" not found
eigenlayer-1  | 
eigenlayer-1  | 
eigenlayer-1  | Error: script failed: vm.envString: environment variable "OPERATOR_ID" not found
eigenlayer-1  | Error: Failed to register operator 0x11D076Ad347ffB26024C0B815001B60bC25a6B52
```

**Comment by RonTuretzky** [comment]
> @hudsonhrh what is this error?
> ```console
> eigenlayer-1  |   [4161] RegisterOperator::run()
> eigenlayer-1  |     ├─ [0] VM::envString("OPERATOR_ID") [staticcall]
> eigenlayer-1  |     │   └─ ← [Revert] vm.envString: environment variable "OPERATOR_ID" not found
> eigenlayer-1  |     └─ ← [Revert] vm.envString: environment variable "OPERATOR_ID" not found
> eigenlayer-1  | 
> eigenlayer-1  | 
> eigenlayer-1  | Error: script failed: vm.envString: environment variable "OPERATOR_ID" not found
> eigenlayer-1  | Error: Failed to register operator 0x11D076Ad347ffB26024C0B815001B60bC25a6B52
> ```

Check the readme , you need the new config

**Comment by hudsonhrh** [comment]
> @hudsonhrh what is this error?
> 
> ```
> eigenlayer-1  |   [4161] RegisterOperator::run()
> eigenlayer-1  |     ├─ [0] VM::envString("OPERATOR_ID") [staticcall]
> eigenlayer-1  |     │   └─ ← [Revert] vm.envString: environment variable "OPERATOR_ID" not found
> eigenlayer-1  |     └─ ← [Revert] vm.envString: environment variable "OPERATOR_ID" not found
> eigenlayer-1  | 
> eigenlayer-1  | 
> eigenlayer-1  | Error: script failed: vm.envString: environment variable "OPERATOR_ID" not found
> eigenlayer-1  | Error: Failed to register operator 0x11D076Ad347ffB26024C0B815001B60bC25a6B52
> ```

merged dev into this so now it has latest config.json compatible with bls-lcoal. tested it again on my machine and this solution works still

File: docker/eigenlayer/main.sh [hunk 1]
```diff
@@ -119,8 +138,6 @@ for i in $(seq 1 $num_accounts); do
         echo "Error: Failed to register operator $OPERATOR_ADDRESS"
     fi
     
-    OPERATOR_ADDRESS=$(cast wallet address --private-key $OPERATOR_PRIVATE_KEY)
```
Comment (RonTuretzky) [inline docker/eigenlayer/main.sh:122]: why are we removing this?

Comment (hudsonhrh) [reply docker/eigenlayer/main.sh:122]: it was moved not removed. needed to be early

Comment (hudsonhrh) [reply docker/eigenlayer/main.sh:122]: look at line 108 first of the new changes

**Comment by RonTuretzky** [comment]
Getting 
image

debugging

**Comment by RonTuretzky** [comment]
> Getting image
> 
> debugging

was missing allo manager in env 
re-running

**Review by RonTuretzky — APPROVED** [review]
Working on my machine but would wait for @rubydusa
